---
adminUserName: null
api:
  apiServer:
    internalPort: 9000
    port: 0
    timeouts:
      idle: 900
      read: 900
      readHeader: 10
      write: 900
    url: ""
  authProxy:
    caCert: ""
    host: ""
  image: ghcr.io/kyma-project/cfapi/korifi-api-0.0.0@sha256:34311f2f3685fe7ef06c2f35d6e9801635f00f8dab2971fc519e75e1125ab2e7
  include: true
  infoConfig:
    custom: {}
    description: Korifi Cloud Foundry Environment
    minCLIVersion: ""
    name: korifi
    recommendedCLIVersion: ""
    supportAddress: https://www.cloudfoundry.org/technology/korifi/
  lifecycle:
    stack: cflinuxfs3
    type: buildpack
  logcache:
    url: ""
  nodeSelector: {}
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 100Mi
  tolerations: []
  uaaURL: ""
  userCertificateExpirationWarningDuration: 168h
containerRegistryCACertSecret: null
containerRegistrySecrets:
  - image-registry-credentials
controllers:
  extraVCAPApplicationValues: {}
  image: ghcr.io/kyma-project/cfapi/korifi-controllers-0.0.0@sha256:ce7c511ccbce675f5954d1ecd99bc960a710dd8f79fc9f3ff5bc40804523c0b1
  maxRetainedBuildsPerApp: 5
  maxRetainedPackagesPerApp: 5
  namespaceLabels: {}
  nodeSelector: {}
  processDefaults:
    diskQuotaMB: 1024
    memoryMB: 1024
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 100Mi
  taskTTL: 30d
  tolerations: []
  workloadsTLSSecret: korifi-workloads-ingress-cert
debug: false
defaultAppDomainName: null
eksContainerRegistryRoleARN: ""
generateIngressCertificates: false
helm:
  hooksImage: alpine/k8s:1.25.2
jobTaskRunner:
  include: true
  jobTTL: 24h
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  temporarySetPodSeccompProfile: false
kpackImageBuilder:
  builderReadinessTimeout: 30s
  builderRepository: ""
  clusterBuilderName: ""
  clusterStackBuildImage: paketobuildpacks/build-jammy-full
  clusterStackID: io.buildpacks.stacks.jammy
  clusterStackRunImage: paketobuildpacks/run-jammy-full
  include: true
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 100Mi
logLevel: info
networking:
  gatewayClass: null
reconcilers:
  build: kpack-image-builder
  run: statefulset-runner
rootNamespace: cf
stagingRequirements:
  buildCacheMB: 2048
  diskMB: 0
  memoryMB: 0
statefulsetRunner:
  include: true
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  temporarySetPodSeccompProfile: false
systemImagePullSecrets: []
