{{- if not (lookup "v1" "Secret" .Values.destinationNamespace .Values.destinationSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.destinationSecret }}
  namespace: {{ .Values.destinationNamespace }}
data:
  .dockerconfigjson: {{ index (lookup "v1" "Secret" .Values.sourceNamespace .Values.sourceSecret).data ".dockerconfigjson" }}
type: kubernetes.io/dockerconfigjson
{{- end -}}
