// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"github.com/kyma-project/cfapi/api/v1alpha1"
	"github.com/kyma-project/cfapi/controllers/installable"
)

type Uninstallable struct {
	UninstallStub        func(context.Context, v1alpha1.InstallationConfig, installable.EventRecorder) (installable.Result, error)
	uninstallMutex       sync.RWMutex
	uninstallArgsForCall []struct {
		arg1 context.Context
		arg2 v1alpha1.InstallationConfig
		arg3 installable.EventRecorder
	}
	uninstallReturns struct {
		result1 installable.Result
		result2 error
	}
	uninstallReturnsOnCall map[int]struct {
		result1 installable.Result
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Uninstallable) Uninstall(arg1 context.Context, arg2 v1alpha1.InstallationConfig, arg3 installable.EventRecorder) (installable.Result, error) {
	fake.uninstallMutex.Lock()
	ret, specificReturn := fake.uninstallReturnsOnCall[len(fake.uninstallArgsForCall)]
	fake.uninstallArgsForCall = append(fake.uninstallArgsForCall, struct {
		arg1 context.Context
		arg2 v1alpha1.InstallationConfig
		arg3 installable.EventRecorder
	}{arg1, arg2, arg3})
	stub := fake.UninstallStub
	fakeReturns := fake.uninstallReturns
	fake.recordInvocation("Uninstall", []interface{}{arg1, arg2, arg3})
	fake.uninstallMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Uninstallable) UninstallCallCount() int {
	fake.uninstallMutex.RLock()
	defer fake.uninstallMutex.RUnlock()
	return len(fake.uninstallArgsForCall)
}

func (fake *Uninstallable) UninstallCalls(stub func(context.Context, v1alpha1.InstallationConfig, installable.EventRecorder) (installable.Result, error)) {
	fake.uninstallMutex.Lock()
	defer fake.uninstallMutex.Unlock()
	fake.UninstallStub = stub
}

func (fake *Uninstallable) UninstallArgsForCall(i int) (context.Context, v1alpha1.InstallationConfig, installable.EventRecorder) {
	fake.uninstallMutex.RLock()
	defer fake.uninstallMutex.RUnlock()
	argsForCall := fake.uninstallArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Uninstallable) UninstallReturns(result1 installable.Result, result2 error) {
	fake.uninstallMutex.Lock()
	defer fake.uninstallMutex.Unlock()
	fake.UninstallStub = nil
	fake.uninstallReturns = struct {
		result1 installable.Result
		result2 error
	}{result1, result2}
}

func (fake *Uninstallable) UninstallReturnsOnCall(i int, result1 installable.Result, result2 error) {
	fake.uninstallMutex.Lock()
	defer fake.uninstallMutex.Unlock()
	fake.UninstallStub = nil
	if fake.uninstallReturnsOnCall == nil {
		fake.uninstallReturnsOnCall = make(map[int]struct {
			result1 installable.Result
			result2 error
		})
	}
	fake.uninstallReturnsOnCall[i] = struct {
		result1 installable.Result
		result2 error
	}{result1, result2}
}

func (fake *Uninstallable) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Uninstallable) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ installable.Uninstallable = new(Uninstallable)
