apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: tests/vendor
  contents:
  - path: istio
    git:
      url: https://github.com/istio/istio
      depth: 1
      refSelection:
        semver:
          constraints: ">=1.27.0"
    includePaths:
      - manifests/charts/base/files/crd-all.gen.yaml
    newRootPath: manifests/charts/base/files
  - path: docker-registry
    githubRelease:
      slug: kyma-project/docker-registry
      latest: true
      disableAutoChecksumValidation: true
      assetNames: ["dockerregistry-operator.yaml"]

- path: module-data/vendor
  contents:
  - path: gateway-api
    githubRelease:
      slug: kubernetes-sigs/gateway-api
      latest: true
      disableAutoChecksumValidation: true
      assetNames: ["experimental-install.yaml"]
