apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-api-ingress-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ .Values.cfDomain }}"
  dnsNames:
  - "cfapi.{{ .Values.cfDomain }}"
  - "*.apps.{{ .Values.cfDomain }}"
  isCA: {{ .Values.useSelfSignedCertificates }}
  secretRef:
    name: korifi-api-ingress-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-workloads-ingress-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ .Values.cfDomain }}"
  dnsNames:
  - "*.apps.{{ .Values.cfDomain }}"
  isCA: {{ .Values.useSelfSignedCertificates }}
  secretRef:
    name: korifi-workloads-ingress-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-api-internal-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: korifi-api-svc.korifi
  dnsNames:
  - korifi-api-svc.korifi.svc.cluster.local
  isCA: true
  issuerRef:
    name: kim-snatch-kyma
    namespace: kyma-system
  secretRef:
    name: korifi-api-internal-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-controllers-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: korifi-controllers-webhook-service.korifi
  dnsNames:
  - korifi-controllers-webhook-service.korifi.svc
  - korifi-controllers-webhook-service.korifi.svc.cluster.local
  isCA: true
  issuerRef:
    name: kim-snatch-kyma
    namespace: kyma-system
  secretRef:
    name: korifi-controllers-webhook-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-kpack-image-builder-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: korifi-kpack-image-builder-webhook-service.korifi
  dnsNames:
  - korifi-kpack-image-builder-webhook-service.korifi.svc
  - korifi-kpack-image-builder-webhook-service.korifi.svc.cluster.local
  isCA: true
  issuerRef:
    name: kim-snatch-kyma
    namespace: kyma-system
  secretRef:
    name: korifi-kpack-image-builder-webhook-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-statefulset-runner-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: korifi-statefulset-runner-webhook-service.korifi
  dnsNames:
  - korifi-statefulset-runner-webhook-service.korifi.svc
  - korifi-statefulset-runner-webhook-service.korifi.svc.cluster.local
  isCA: true
  issuerRef:
    name: kim-snatch-kyma
    namespace: kyma-system
  secretRef:
    name: korifi-statefulset-runner-webhook-cert
    namespace: {{ .Release.Namespace }}
