apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-api-ingress-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ .Values.cfDomain }}"
  dnsNames:
  - "cfapi.{{ .Values.cfDomain }}"
# Gardener cert manager does not allow specifying isCA for non-self-signed certifcates event to false
{{- if .Values.useSelfSignedCertificates }}
  isCA: true
{{ end }}
  secretRef:
    name: korifi-api-ingress-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-workloads-ingress-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "apps.{{ .Values.cfDomain }}"
  dnsNames:
  - "*.apps.{{ .Values.cfDomain }}"
# Gardener cert manager does not allow specifying isCA for non-self-signed certifcates event to false
{{- if .Values.useSelfSignedCertificates }}
  isCA: true
{{ end }}
  secretRef:
    name: korifi-workloads-ingress-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-api-internal-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: korifi-api-svc.korifi
  dnsNames:
  - korifi-api-svc.korifi.svc.cluster.local
  isCA: true
  issuerRef:
    name: {{ .Values.selfSignedIssuer }}
    namespace: {{ .Values.systemNamespace }}
  secretRef:
    name: korifi-api-internal-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-controllers-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: korifi-controllers-webhook-service.korifi
  dnsNames:
  - korifi-controllers-webhook-service.korifi.svc
  - korifi-controllers-webhook-service.korifi.svc.cluster.local
  isCA: true
  issuerRef:
    name: {{ .Values.selfSignedIssuer }}
    namespace: {{ .Values.systemNamespace }}
  secretRef:
    name: korifi-controllers-webhook-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-kpack-image-builder-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: korifi-kpack-image-builder-webhook-service.korifi
  dnsNames:
  - korifi-kpack-image-builder-webhook-service.korifi.svc
  - korifi-kpack-image-builder-webhook-service.korifi.svc.cluster.local
  isCA: true
  issuerRef:
    name: {{ .Values.selfSignedIssuer }}
    namespace: {{ .Values.systemNamespace }}
  secretRef:
    name: korifi-kpack-image-builder-webhook-cert
    namespace: {{ .Release.Namespace }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: korifi-statefulset-runner-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: korifi-statefulset-runner-webhook-service.korifi
  dnsNames:
  - korifi-statefulset-runner-webhook-service.korifi.svc
  - korifi-statefulset-runner-webhook-service.korifi.svc.cluster.local
  isCA: true
  issuerRef:
    name: {{ .Values.selfSignedIssuer }}
    namespace: {{ .Values.systemNamespace }}
  secretRef:
    name: korifi-statefulset-runner-webhook-cert
    namespace: {{ .Release.Namespace }}
