{{- with .Values.containerRegistrySecret }}
{{- if .propagation.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .propagation.destinationNamespace }}
data:
  .dockerconfigjson: {{ index (lookup "v1" "Secret" .propagation.sourceNamespace .name).data ".dockerconfigjson" }}
type: kubernetes.io/dockerconfigjson
{{- end -}}
{{- end -}}
