apiVersion: v1
kind: Service
metadata:
  labels:
    app: btp-service-broker
  name: btp-service-broker-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: btp-service-broker
  type: ClusterIP
