apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: btp-service-broker-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: btp-service-broker-role
subjects:
- kind: ServiceAccount
  name: btp-service-broker-serviceaccount
  namespace: cfapi-system
