apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: btp-service-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: btp-service-broker
subjects:
- kind: ServiceAccount
  name: btp-service-broker
  namespace: cfapi-system
