apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: btp-service-broker-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
  - apiGroups:
    - services.cloud.sap.com
    resources:
    - servicebindings
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - services.cloud.sap.com
    resources:
    - serviceinstances
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
