apiVersion: v1
kind: ConfigMap
metadata:
  name: korifi-kpack-image-builder-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    cfRootNamespace: {{ .Values.rootNamespace }}
    clusterBuilderName: {{ .Values.kpackImageBuilder.clusterBuilderName | default "cf-kpack-cluster-builder" }}
    builderReadinessTimeout: {{ required "builderReadinessTimeout is required" .Values.kpackImageBuilder.builderReadinessTimeout }}
    containerRepositoryPrefix: {{ .Values.containerRepositoryPrefix | quote }}
    builderServiceAccount: kpack-service-account
    cfStagingResources:
      buildCacheMB: {{ .Values.stagingRequirements.buildCacheMB }}
      diskMB: {{ .Values.stagingRequirements.diskMB }}
      memoryMB: {{ .Values.stagingRequirements.memoryMB }}
    {{- if .Values.eksContainerRegistryRoleARN }}
    containerRegistryType: "ECR"
    {{- end }}
