---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: korifi-kpack-image-builder-controller-manager
  namespace: {{ .Release.Namespace }}
  {{- if .Values.eksContainerRegistryRoleARN }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.eksContainerRegistryRoleARN }}
  {{- end }}
imagePullSecrets:
{{- range .Values.systemImagePullSecrets }}
- name: {{ . | quote }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: korifi-kpack-image-builder-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: korifi-controllers-leader-election-role
subjects:
- kind: ServiceAccount
  name: korifi-kpack-image-builder-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korifi-kpack-image-builder-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-kpack-build-manager-role
subjects:
- kind: ServiceAccount
  name: korifi-kpack-image-builder-controller-manager
  namespace: {{ .Release.Namespace }}
