apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: korifi
  namespace: cfapi-system
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: HelmChart
    name: korifi
    namespace: cfapi-system
  releaseName: korifi
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
