---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: korifi-job-task-runner-controller-manager
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{- range .Values.systemImagePullSecrets }}
- name: {{ . | quote }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: korifi-job-task-runner-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: korifi-controllers-leader-election-role
subjects:
- kind: ServiceAccount
  name: korifi-job-task-runner-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korifi-job-task-runner-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-job-task-runner-taskworkload-manager-role
subjects:
- kind: ServiceAccount
  name: korifi-job-task-runner-controller-manager
  namespace: {{ .Release.Namespace }}
