// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"

	"github.com/kyma-project/cfapi/components/btp-service-broker/btp"
)

type CredentialsDecoder struct {
	DecodeBindingSecretDataStub        func(map[string][]byte) (any, error)
	decodeBindingSecretDataMutex       sync.RWMutex
	decodeBindingSecretDataArgsForCall []struct {
		arg1 map[string][]byte
	}
	decodeBindingSecretDataReturns struct {
		result1 any
		result2 error
	}
	decodeBindingSecretDataReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CredentialsDecoder) DecodeBindingSecretData(arg1 map[string][]byte) (any, error) {
	fake.decodeBindingSecretDataMutex.Lock()
	ret, specificReturn := fake.decodeBindingSecretDataReturnsOnCall[len(fake.decodeBindingSecretDataArgsForCall)]
	fake.decodeBindingSecretDataArgsForCall = append(fake.decodeBindingSecretDataArgsForCall, struct {
		arg1 map[string][]byte
	}{arg1})
	stub := fake.DecodeBindingSecretDataStub
	fakeReturns := fake.decodeBindingSecretDataReturns
	fake.recordInvocation("DecodeBindingSecretData", []interface{}{arg1})
	fake.decodeBindingSecretDataMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CredentialsDecoder) DecodeBindingSecretDataCallCount() int {
	fake.decodeBindingSecretDataMutex.RLock()
	defer fake.decodeBindingSecretDataMutex.RUnlock()
	return len(fake.decodeBindingSecretDataArgsForCall)
}

func (fake *CredentialsDecoder) DecodeBindingSecretDataCalls(stub func(map[string][]byte) (any, error)) {
	fake.decodeBindingSecretDataMutex.Lock()
	defer fake.decodeBindingSecretDataMutex.Unlock()
	fake.DecodeBindingSecretDataStub = stub
}

func (fake *CredentialsDecoder) DecodeBindingSecretDataArgsForCall(i int) map[string][]byte {
	fake.decodeBindingSecretDataMutex.RLock()
	defer fake.decodeBindingSecretDataMutex.RUnlock()
	argsForCall := fake.decodeBindingSecretDataArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CredentialsDecoder) DecodeBindingSecretDataReturns(result1 any, result2 error) {
	fake.decodeBindingSecretDataMutex.Lock()
	defer fake.decodeBindingSecretDataMutex.Unlock()
	fake.DecodeBindingSecretDataStub = nil
	fake.decodeBindingSecretDataReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *CredentialsDecoder) DecodeBindingSecretDataReturnsOnCall(i int, result1 any, result2 error) {
	fake.decodeBindingSecretDataMutex.Lock()
	defer fake.decodeBindingSecretDataMutex.Unlock()
	fake.DecodeBindingSecretDataStub = nil
	if fake.decodeBindingSecretDataReturnsOnCall == nil {
		fake.decodeBindingSecretDataReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.decodeBindingSecretDataReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *CredentialsDecoder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CredentialsDecoder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ btp.CredentialsDecoder = new(CredentialsDecoder)
