name: Release-Genkubeconfig-Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/kyma-project/cfapi

jobs:
  build:
    runs-on: [ self-hosted ]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push genkubeconfig image
      shell: bash
      working-directory: 'tools/kubeconfig'
      run: |
        docker build -t ${{ env.REGISTRY }}/genkubeconfig .
        docker push ${{ env.REGISTRY }}/genkubeconfig


