name: Publish Release Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:  
      - name: set version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
        id: version

      - name: Publish Release
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          gh release edit "${VERSION}" --draft=false --latest
  
