name: Run Integration Tests

on:
  push:
    branches: [ "**" ]   # remove after testing
  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: cfapi
        node_image: kindest/node:v1.29.2

    - name: Run tests
      run: make test-integration
