apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sap.ids:georgi.sabev@sap.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sap.ids:danail.branekov@sap.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sap.ids:samir.zeort@sap.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sap.ids:yusmen.zabanov@sap.com
